### ISSUE TITLE
A bug with two copies of the same post

### ISSUE THREAD

**Issue by hugmouse** [vas3k/infomate.club#12]
# Demonstration

Url: https://infomate.club/backlog_and_money/

![image](https://user-images.githubusercontent.com/44648612/73118029-2d38fb80-3f89-11ea-82ba-aa6c6d95d9c8.png)
![image](https://user-images.githubusercontent.com/44648612/73118056-7be69580-3f89-11ea-8537-80875029ddd7.png)
![image](https://user-images.githubusercontent.com/44648612/73118058-82750d00-3f89-11ea-8a3a-dbf006abf569.png)
![image](https://user-images.githubusercontent.com/44648612/73118062-8c970b80-3f89-11ea-8727-0807129a8b4c.png)
![image](https://user-images.githubusercontent.com/44648612/73118065-9f114500-3f89-11ea-9231-28e8820c771d.png)

## Addtitional bug

There's also a duplicate in the preview.

![image](https://user-images.githubusercontent.com/44648612/73118028-2d38fb80-3f89-11ea-9850-4fd5ecd11a65.png)
![image](https://user-images.githubusercontent.com/44648612/73118030-2dd19200-3f89-11ea-80ee-3d00d227fd93.png)

**Comment by vas3k** [comment]
Caching issue related to a migration to a new Telegram -> RSS service. The old one banned my IP :D 
Should be fixed now.
