### ISSUE TITLE
A bug with headers 

### ISSUE THREAD

**Issue by 0gnev** [vas3k/infomate.club#13]
Issue in "Hodl Hodl News".
"&uArr;" in the beginning of header
![photo_2020-01-27_22-38-03](https://user-images.githubusercontent.com/49639884/73188616-b9981980-4155-11ea-83bb-a815f40f7d53.jpg)

**Comment by vas3k** [comment]
Nice catch. Someone can make a PR for that :)

**Comment by hugmouse** [comment]
Also here:

![firefox_xmSWsvjYWe](https://user-images.githubusercontent.com/44648612/73587534-26b20300-44f8-11ea-94d8-0a8c770a7b33.png)

https://vc.ru/marketing/104484-burger-king-v-tokio-provodil-zakryvshiysya-po-sosedstvu-mcdonald-s-plakatom-s-blagodarnostyu-za-konkurenciyu?from=rss

**Comment by vasiliy-garenskikh** [comment]
Can we close this issue?
