### ISSUE TITLE
The next web cloudflare ban

### ISSUE THREAD

**Issue by DarkFlame57** [vas3k/infomate.club#33]
Screenshot speaks for itself.
![Снимок экрана 2020-07-04 в 22 17 09](https://user-images.githubusercontent.com/49563183/86519592-c4fa1a00-be44-11ea-8237-3af3354bfb21.png)

**Comment by Tonna** [comment]
@DarkFlame57 I just check CNET feed on https://infomate.club/tech/ page and it looks fine.
