### ISSUE TITLE
"Unused" boards removed

### ISSUE THREAD

**Issue by vintagentleman** [vas3k/infomate.club#50]
Why did you do [such a thing](https://github.com/vas3k/infomate.club/commit/8759957b0e3814b8be7b80bc3248c1cda04430cb)?

Even if those boards were no longer actively maintained, who's to say they couldn't nor wouldn't be useful as a reference list?

**Comment by vas3k** [comment]
Feeds in these boards were mostly broken and authors didn’t care. This created a sense of abandonment of the site as a whole. Feel free to recreate them if you want to maintain it, git has all the history.

**Comment by vintagentleman** [comment]
Okay, thanks for the feedback!
