### ISSUE TITLE
Add CI support

### ISSUE THREAD

**Issue by vovinacci** [vas3k/infomate.club#6]
Hi,

  To be able to run linters against PRs to ensure, shall we add external CI integration? For example, https://travis-ci.org/ is free for open-source projects.
Target goal is to be able to run linter and mypy to ensure that PR quality didn't drop.
Later this could extended with tests and other fancy things if necessary.

What do you think? I can create PR to have this in place.

**Comment by vas3k** [comment]
Travis CI is nice for such a small project. I'm all for adding it.
The only problem is that we don't have any tests to run on it :D
So it's basically just gonna check that the Docker started without any errors.

**Comment by vovinacci** [comment]
@vas3k Oki do then, I'll open PR later on today and will ask you to setup Travis.

**Comment by vovinacci** [comment]
@vas3k Re setting up Travis - this should be easy.
Once you have account there:
- Go to https://travis-ci.org/
- click `+` on the right of `My Repositories` and choose `infomate.club`
- It's safe to leave building PRs and branches

**Comment by vovinacci** [comment]
Should you need any help in setting up things - let me know, I'll help.

**Comment by vas3k** [comment]
Sorry for the delay. Merged the PR, activated Travis
